receivers:
  - name: 'robusta'
    webhook_configs:
      - url: 'http://robusta-runner.robusta.svc.cluster.local/api/alerts'
        send_resolved: true
  - name: 'default-receiver'

route:
  routes:
    - receiver: 'robusta'
      group_by: [ '...' ]
      group_wait: 1s
      group_interval: 1s
      matchers:
        - severity =~ ".*"
      repeat_interval: 4h
      continue: true 
  receiver: 'default-receiver'
