apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-error-deployment
  labels:
    app: nginx-error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-error
  template:
    metadata:
      labels:
        app: nginx-error
    spec:
      containers:
      - name: nginx
        image: nginx:invalid-version
        ports:
        - containerPort: 80
